
asav = {
        "template": "asav",
        "type": "qemu",
        "count": "1",
        "image": "asav-941-200",
        "name": "ASAv",
        "icon": "ASA.png",
        "uuid": "",
        "cpulimit": "",
        "cpu": "1",
        "ram": "2048",
        "ethernet": "8",
        "qemu_version": "",
        "qemu_arch": "",
        "qemu_nic": "",
        "qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -no-user-config -cpu host -nodefaults -display none -vga std -rtc base=utc",
        "ro_qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -no-user-config -cpu host -nodefaults -display none -vga std -rtc base=utc",
        "config": "0",
        "delay": "0",
        "console": "telnet",
        "left": "1091",
        "top": "118",
        "postfix": 0,
    }
iol = {
        "template": "iol",
        "type": "iol",
        "count": "1",
        "image": "i86bi_linux_l2-adventerprisek9-ms.SSA.high_iron_20180510.bin",
        "name": "R",
        "icon": "Router.png",
        "nvram": "1024",
        "ram": "1024",
        "ethernet": "1",
        "serial": "0",
        "config": "0",
        "delay": "0",
        "left": "210",
        "top": "249",
        "postfix": 0,
    },
c1710 = {
        "template": "c1710",
        "type": "dynamips",
        "count": "1",
        "image": "c1710-bk9no3r2sy-mz.124-23.image",
        "name": "1710",
        "icon": "Router2.png",
        "idlepc": "0x80369ac4",
        "nvram": "128",
        "ram": "96",
        "config": "0",
        "delay": "0",
        "left": "1048",
        "top": "489",
        "postfix": 0,
    },
c3725 = {
        "template": "c3725",
        "type": "dynamips",
        "count": "1",
        "image": "c3725-adventerprisek9-mz.124-15.T14.image",
        "name": "3725",
        "icon": "Router.png",
        "idlepc": "0x60c08728",
        "nvram": "128",
        "ram": "256",
        "slot1": "NM-1FE-TX",
        "slot2": "NM-16ESW",
        "config": "0",
        "delay": "0",
        "left": "202",
        "top": "435",
        "postfix": 0,
    },
c7200 = {
        "template": "c7200",
        "type": "dynamips",
        "count": "1",
        "image": "c7200-adventerprisek9-mz.152-4.S7.image",
        "name": "7206VXR",
        "icon": "Router.png",
        "idlepc": "0x62f21000",
        "nvram": "128",
        "ram": "256",
        "slot1": "PA-4E",
        "slot2": "PA-4E",
        "slot3": "",
        "slot4": "",
        "slot5": "",
        "slot6": "",
        "config": "0",
        "delay": "0",
        "left": "333",
        "top": "510",
        "postfix": 0,
    },
nxosv9k = {
        "template": "nxosv9k",
        "type": "qemu",
        "count": "1",
        "image": "nxosv9k-7.0.3.I7.4",
        "name": "NXOS",
        "icon": "Nexus7K.png",
        "uuid": "",
        "cpulimit": "undefined",
        "cpu": "2",
        "ram": "8192",
        "ethernet": "8",
        "qemu_version": "",
        "qemu_arch": "",
        "qemu_nic": "",
        "qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -enable-kvm -cpu host",
        "ro_qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -enable-kvm -cpu host",
        "config": "0",
        "delay": "0",
        "console": "telnet",
        "left": "208",
        "top": "400",
        "postfix": 0,
    },
viosl2 = {
        "template": "viosl2",
        "type": "qemu",
        "count": "1",
        "image": "viosl2-adventerprisek9-m.SSA.high_iron_20200929",
        "name": "Switch",
        "icon": "Switch.png",
        "uuid": "",
        "cpulimit": "undefined",
        "cpu": "1",
        "ram": "1024",
        "ethernet": "8",
        "qemu_version": "",
        "qemu_arch": "",
        "qemu_nic": "",
        "qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -no-user-config -nodefaults -rtc base=utc -cpu host",
        "ro_qemu_options": "-machine type=pc,accel=kvm -serial mon:stdio -nographic -no-user-config -nodefaults -rtc base=utc -cpu host",
        "config": "0",
        "delay": "0",
        "console": "telnet",
        "left": "251",
        "top": "466",
        "postfix": 0,
    },
vpcs = {
        "template": "vpcs",
        "type": "vpcs",
        "count": "1",
        "name": "VPC",
        "icon": "Laptop.png",
        "config": "0",
        "delay": "0",
        "left": "264",
        "top": "332",
        "postfix": 0,
    },

